### PR TITLE
Correctly track and expose windows opened from secondary windows, and so on

### PR DESCRIPTION
**Pull request by dennisverspuij**

### CODE REVIEW

**Comment by jcalderonzumba** [comment]
Awesome PR!!!, i will check it as soon as possible.

**Comment by jcalderonzumba** [comment]
Looks good to me 👍

**Comment by dennisverspuij** [comment]
Thanks Juan, any chance releasing this as 1.2.0 ?

**Comment by jcalderonzumba** [comment]
yes, i need to tag it and release.

**Comment by dennisverspuij** [comment]
Would be great, please do. Thanks!

**Comment by jcalderonzumba** [comment]
@dennisverspuij  tagged, i'm so sorry for the delays but i've been very busy.

**Comment by dennisverspuij** [comment]
@jcalderonzumba No problem, many thanks!

**Pull request merged**
