### PR TITLE
Use guzzle6 instead of guzzle 5

### PR DESCRIPTION
**Pull request by dawehner**
Solves https://github.com/jcalderonzumba/gastonjs/issues/14

### CODE REVIEW

**Comment by jcalderonzumba** [comment]
Check https://travis-ci.org/jcalderonzumba/gastonjs/builds/83550068, test do not pass with this PR.

**Comment by jcalderonzumba** [comment]
Also i've just check the error messages, guzzle6 does not support php 5.4. Could you elaborate a bit more on why we should use guzzle6 instead of guzzle5?.

**Comment by dawehner** [comment]
```
Also i've just check the error messages, guzzle6 does not support php 5.4. Could you elaborate a bit more on why we should use guzzle6 instead of guzzle5?.
```

We as in Drupal would like to introduce frontend testing using phantomjs. We already use a the default mink driver, but would like to not have to use selenium.

In general I think php 5.4 is not a hard requirement anymore. Its hard to find even a hoster without support for 5.5, and well, all your users have your own servers / a proper hosting anyway.

**Comment by dawehner** [comment]
Sorry I didn't really answer your question. We as in Drupal want to bundle our release in the next time
with a stable version of every library we use. Given that guzzle 6 will have support for much longer than guzzle 5. Its also the current stable version.

**Comment by jcalderonzumba** [comment]
Ok, will give a thought about supporting 5.4 or not, because in the end this becomes an issue of dropping support of old PHP versions.
Thanks a lot for helping gastonJS to grow.
@stof What do you think about this?

**Comment by stof** [comment]
given the small size of changes necessary here, it may be even better to support both Guzzle 5 and Guzzle 6 (detecting which version is installed).
this way, the driver will be usable for people using any of these versions (in many cases, updating from 5 to 6 is much more complex and so projects may still be stuck to guzzle 5)

**Comment by jibran** [comment]
+1 to supporting both version for now.

**Comment by dawehner** [comment]
If this works this would be really cool!
What about doing that? Checking for the existence of that particular class?

**Comment by dawehner** [comment]
Mh, anyone might have a clue why this fails?

**Comment by jcalderonzumba** [comment]
Now is green, sometimes there are random phantomJS crashes. Is something that happens from time to time.

**Comment by dawehner** [comment]
Cool, thank you!

**Pull request merged**
